<?php
/**
 * @package     currencyconverter
 * @author      Dan Gibbs <dan@goldcoastmedia.co.uk>
 * @copyright   Copyright (c) 2012 Gold Coast Media Ltd
 * @subpackage  lexicon
 * @language    en
 */
$_lang['currencyconverter'] = 'Currency Converter';

// Error Strings
$_lang['currencyconverter.error_fetch_feed']   = 'Error reading [[+url]].';
$_lang['currencyconverter.error_parsing_feed'] = 'Error parsing exchange rate feed.';
$_lang['currencyconverter.error_feed_failed']  = 'Error reading exchange rate data. Check/change any parameters that could potentially cause this.';
$_lang['currencyconverter.error_api']          = '[[+status]] error. [[+message]]: [[+description]]';
$_lang['currencyconverter.error_unknown_code'] = '[[+code]] currency code unknown.';

// System Settings
$_lang['setting_currencyconverter.appid']              = 'App ID';
$_lang['setting_currencyconverter.appid_desc']         = 'App ID for openexchangerates.org API requests.';

$_lang['setting_currencyconverter.cachelifetime']      = 'Cache Lifetime';
$_lang['setting_currencyconverter.cachelifetime_desc'] = 'The default cache lifetime (in seconds) for currency exchange rates. IMPORTANT: If you are using the \'free plan\' you are limited to a maximum of 1000 API request per month (approximately 1.3 requests per hour).';

$_lang['setting_currencyconverter.defaultcurrency']      = 'Base Currency';
$_lang['setting_currencyconverter.defaultcurrency_desc'] = 'A currency code to be used by default (e.g. GBP, USD, EUR, JPY).';

$_lang['setting_currencyconverter.timeout']            = 'Connection Timeout';
$_lang['setting_currencyconverter.timeout_desc']       = 'The maximum number of seconds before an API request times out.';

// Currency Strings
$_lang['currencyconverter.string_AED'] = 'United Arab Emirates Dirham';
$_lang['currencyconverter.string_AFN'] = 'Afghan Afghani';
$_lang['currencyconverter.string_ALL'] = 'Albanian Lek';
$_lang['currencyconverter.string_AMD'] = 'Armenian Dram';
$_lang['currencyconverter.string_ANG'] = 'Netherlands Antillean Guilder';
$_lang['currencyconverter.string_AOA'] = 'Angolan Kwanza';
$_lang['currencyconverter.string_ARS'] = 'Argentine Peso';
$_lang['currencyconverter.string_AUD'] = 'Australian Dollar';
$_lang['currencyconverter.string_AWG'] = 'Aruban Florin';
$_lang['currencyconverter.string_AZN'] = 'Azerbaijani Manat';
$_lang['currencyconverter.string_BAM'] = 'Bosnia-Herzegovina Convertible Mark';
$_lang['currencyconverter.string_BBD'] = 'Barbadian Dollar';
$_lang['currencyconverter.string_BDT'] = 'Bangladeshi Taka';
$_lang['currencyconverter.string_BGN'] = 'Bulgarian Lev';
$_lang['currencyconverter.string_BHD'] = 'Bahraini Dinar';
$_lang['currencyconverter.string_BIF'] = 'Burundian Franc';
$_lang['currencyconverter.string_BMD'] = 'Bermudan Dollar';
$_lang['currencyconverter.string_BND'] = 'Brunei Dollar';
$_lang['currencyconverter.string_BOB'] = 'Bolivian Boliviano';
$_lang['currencyconverter.string_BRL'] = 'Brazilian Real';
$_lang['currencyconverter.string_BSD'] = 'Bahamian Dollar';
$_lang['currencyconverter.string_BTN'] = 'Bhutanese Ngultrum';
$_lang['currencyconverter.string_BWP'] = 'Botswanan Pula';
$_lang['currencyconverter.string_BYR'] = 'Belarusian Ruble';
$_lang['currencyconverter.string_BZD'] = 'Belize Dollar';
$_lang['currencyconverter.string_CAD'] = 'Canadian Dollar';
$_lang['currencyconverter.string_CDF'] = 'Congolese Franc';
$_lang['currencyconverter.string_CHF'] = 'Swiss Franc';
$_lang['currencyconverter.string_CLF'] = 'Chilean Unit of Account (UF)';
$_lang['currencyconverter.string_CLP'] = 'Chilean Peso';
$_lang['currencyconverter.string_CNY'] = 'Chinese Yuan';
$_lang['currencyconverter.string_COP'] = 'Colombian Peso';
$_lang['currencyconverter.string_CRC'] = 'Costa Rican Colón';
$_lang['currencyconverter.string_CUP'] = 'Cuban Peso';
$_lang['currencyconverter.string_CVE'] = 'Cape Verdean Escudo';
$_lang['currencyconverter.string_CZK'] = 'Czech Republic Koruna';
$_lang['currencyconverter.string_DJF'] = 'Djiboutian Franc';
$_lang['currencyconverter.string_DKK'] = 'Danish Krone';
$_lang['currencyconverter.string_DOP'] = 'Dominican Peso';
$_lang['currencyconverter.string_DZD'] = 'Algerian Dinar';
$_lang['currencyconverter.string_EEK'] = 'Estonian Kroon';
$_lang['currencyconverter.string_EGP'] = 'Egyptian Pound';
$_lang['currencyconverter.string_ETB'] = 'Ethiopian Birr';
$_lang['currencyconverter.string_EUR'] = 'Euro';
$_lang['currencyconverter.string_FJD'] = 'Fijian Dollar';
$_lang['currencyconverter.string_FKP'] = 'Falkland Islands Pound';
$_lang['currencyconverter.string_GBP'] = 'British Pound Sterling';
$_lang['currencyconverter.string_GEL'] = 'Georgian Lari';
$_lang['currencyconverter.string_GHS'] = 'Ghanaian Cedi';
$_lang['currencyconverter.string_GIP'] = 'Gibraltar Pound';
$_lang['currencyconverter.string_GMD'] = 'Gambian Dalasi';
$_lang['currencyconverter.string_GNF'] = 'Guinean Franc';
$_lang['currencyconverter.string_GTQ'] = 'Guatemalan Quetzal';
$_lang['currencyconverter.string_GYD'] = 'Guyanaese Dollar';
$_lang['currencyconverter.string_HKD'] = 'Hong Kong Dollar';
$_lang['currencyconverter.string_HNL'] = 'Honduran Lempira';
$_lang['currencyconverter.string_HRK'] = 'Croatian Kuna';
$_lang['currencyconverter.string_HTG'] = 'Haitian Gourde';
$_lang['currencyconverter.string_HUF'] = 'Hungarian Forint';
$_lang['currencyconverter.string_IDR'] = 'Indonesian Rupiah';
$_lang['currencyconverter.string_ILS'] = 'Israeli New Sheqel';
$_lang['currencyconverter.string_INR'] = 'Indian Rupee';
$_lang['currencyconverter.string_IQD'] = 'Iraqi Dinar';
$_lang['currencyconverter.string_IRR'] = 'Iranian Rial';
$_lang['currencyconverter.string_ISK'] = 'Icelandic Króna';
$_lang['currencyconverter.string_JEP'] = 'Jersey Pound';
$_lang['currencyconverter.string_JMD'] = 'Jamaican Dollar';
$_lang['currencyconverter.string_JOD'] = 'Jordanian Dinar';
$_lang['currencyconverter.string_JPY'] = 'Japanese Yen';
$_lang['currencyconverter.string_KES'] = 'Kenyan Shilling';
$_lang['currencyconverter.string_KGS'] = 'Kyrgyzstani Som';
$_lang['currencyconverter.string_KHR'] = 'Cambodian Riel';
$_lang['currencyconverter.string_KMF'] = 'Comorian Franc';
$_lang['currencyconverter.string_KPW'] = 'North Korean Won';
$_lang['currencyconverter.string_KRW'] = 'South Korean Won';
$_lang['currencyconverter.string_KWD'] = 'Kuwaiti Dinar';
$_lang['currencyconverter.string_KYD'] = 'Cayman Islands Dollar';
$_lang['currencyconverter.string_KZT'] = 'Kazakhstani Tenge';
$_lang['currencyconverter.string_LAK'] = 'Laotian Kip';
$_lang['currencyconverter.string_LBP'] = 'Lebanese Pound';
$_lang['currencyconverter.string_LKR'] = 'Sri Lankan Rupee';
$_lang['currencyconverter.string_LRD'] = 'Liberian Dollar';
$_lang['currencyconverter.string_LSL'] = 'Lesotho Loti';
$_lang['currencyconverter.string_LTL'] = 'Lithuanian Litas';
$_lang['currencyconverter.string_LVL'] = 'Latvian Lats';
$_lang['currencyconverter.string_LYD'] = 'Libyan Dinar';
$_lang['currencyconverter.string_MAD'] = 'Moroccan Dirham';
$_lang['currencyconverter.string_MDL'] = 'Moldovan Leu';
$_lang['currencyconverter.string_MGA'] = 'Malagasy Ariary';
$_lang['currencyconverter.string_MKD'] = 'Macedonian Denar';
$_lang['currencyconverter.string_MMK'] = 'Myanma Kyat';
$_lang['currencyconverter.string_MNT'] = 'Mongolian Tugrik';
$_lang['currencyconverter.string_MOP'] = 'Macanese Pataca';
$_lang['currencyconverter.string_MRO'] = 'Mauritanian Ouguiya';
$_lang['currencyconverter.string_MUR'] = 'Mauritian Rupee';
$_lang['currencyconverter.string_MVR'] = 'Maldivian Rufiyaa';
$_lang['currencyconverter.string_MWK'] = 'Malawian Kwacha';
$_lang['currencyconverter.string_MXN'] = 'Mexican Peso';
$_lang['currencyconverter.string_MYR'] = 'Malaysian Ringgit';
$_lang['currencyconverter.string_MZN'] = 'Mozambican Metical';
$_lang['currencyconverter.string_NAD'] = 'Namibian Dollar';
$_lang['currencyconverter.string_NGN'] = 'Nigerian Naira';
$_lang['currencyconverter.string_NIO'] = 'Nicaraguan Córdoba';
$_lang['currencyconverter.string_NOK'] = 'Norwegian Krone';
$_lang['currencyconverter.string_NPR'] = 'Nepalese Rupee';
$_lang['currencyconverter.string_NZD'] = 'New Zealand Dollar';
$_lang['currencyconverter.string_OMR'] = 'Omani Rial';
$_lang['currencyconverter.string_PAB'] = 'Panamanian Balboa';
$_lang['currencyconverter.string_PEN'] = 'Peruvian Nuevo Sol';
$_lang['currencyconverter.string_PGK'] = 'Papua New Guinean Kina';
$_lang['currencyconverter.string_PHP'] = 'Philippine Peso';
$_lang['currencyconverter.string_PKR'] = 'Pakistani Rupee';
$_lang['currencyconverter.string_PLN'] = 'Polish Zloty';
$_lang['currencyconverter.string_PYG'] = 'Paraguayan Guarani';
$_lang['currencyconverter.string_QAR'] = 'Qatari Rial';
$_lang['currencyconverter.string_RON'] = 'Romanian Leu';
$_lang['currencyconverter.string_RSD'] = 'Serbian Dinar';
$_lang['currencyconverter.string_RUB'] = 'Russian Ruble';
$_lang['currencyconverter.string_RWF'] = 'Rwandan Franc';
$_lang['currencyconverter.string_SAR'] = 'Saudi Riyal';
$_lang['currencyconverter.string_SBD'] = 'Solomon Islands Dollar';
$_lang['currencyconverter.string_SCR'] = 'Seychellois Rupee';
$_lang['currencyconverter.string_SDG'] = 'Sudanese Pound';
$_lang['currencyconverter.string_SEK'] = 'Swedish Krona';
$_lang['currencyconverter.string_SGD'] = 'Singapore Dollar';
$_lang['currencyconverter.string_SHP'] = 'Saint Helena Pound';
$_lang['currencyconverter.string_SLL'] = 'Sierra Leonean Leone';
$_lang['currencyconverter.string_SOS'] = 'Somali Shilling';
$_lang['currencyconverter.string_SRD'] = 'Surinamese Dollar';
$_lang['currencyconverter.string_STD'] = 'São Tomé and Príncipe Dobra';
$_lang['currencyconverter.string_SVC'] = 'Salvadoran Colón';
$_lang['currencyconverter.string_SYP'] = 'Syrian Pound';
$_lang['currencyconverter.string_SZL'] = 'Swazi Lilangeni';
$_lang['currencyconverter.string_THB'] = 'Thai Baht';
$_lang['currencyconverter.string_TJS'] = 'Tajikistani Somoni';
$_lang['currencyconverter.string_TMT'] = 'Turkmenistani Manat';
$_lang['currencyconverter.string_TND'] = 'Tunisian Dinar';
$_lang['currencyconverter.string_TOP'] = 'Tongan Pa\'anga';
$_lang['currencyconverter.string_TRY'] = 'Turkish Lira';
$_lang['currencyconverter.string_TTD'] = 'Trinidad and Tobago Dollar';
$_lang['currencyconverter.string_TWD'] = 'New Taiwan Dollar';
$_lang['currencyconverter.string_TZS'] = 'Tanzanian Shilling';
$_lang['currencyconverter.string_UAH'] = 'Ukrainian Hryvnia';
$_lang['currencyconverter.string_UGX'] = 'Ugandan Shilling';
$_lang['currencyconverter.string_USD'] = 'United States Dollar';
$_lang['currencyconverter.string_UYU'] = 'Uruguayan Peso';
$_lang['currencyconverter.string_UZS'] = 'Uzbekistan Som';
$_lang['currencyconverter.string_VEF'] = 'Venezuelan Bolívar';
$_lang['currencyconverter.string_VND'] = 'Vietnamese Dong';
$_lang['currencyconverter.string_VUV'] = 'Vanuatu Vatu';
$_lang['currencyconverter.string_WST'] = 'Samoan Tala';
$_lang['currencyconverter.string_XAF'] = 'CFA Franc BEAC';
$_lang['currencyconverter.string_XCD'] = 'East Caribbean Dollar';
$_lang['currencyconverter.string_XDR'] = 'Special Drawing Rights';
$_lang['currencyconverter.string_XOF'] = 'CFA Franc BCEAO';
$_lang['currencyconverter.string_XPF'] = 'CFP Franc';
$_lang['currencyconverter.string_YER'] = 'Yemeni Rial';
$_lang['currencyconverter.string_ZAR'] = 'South African Rand';
$_lang['currencyconverter.string_ZMK'] = 'Zambian Kwacha';
$_lang['currencyconverter.string_ZWL'] = 'Zimbabwean Dollar';

// Decimal Unicode Currency Symbols
$_lang['currencyconverter.symbol_AED'] = '&#1583;.&#1573;'; // ?
$_lang['currencyconverter.symbol_AFN'] = '&#65;&#102;';
$_lang['currencyconverter.symbol_ALL'] = '&#76;&#101;&#107;';
$_lang['currencyconverter.symbol_AMD'] = '';
$_lang['currencyconverter.symbol_ANG'] = '&#402;';
$_lang['currencyconverter.symbol_AOA'] = '&#75;&#122;'; // ?
$_lang['currencyconverter.symbol_ARS'] = '&#36;';
$_lang['currencyconverter.symbol_AUD'] = '&#36;';
$_lang['currencyconverter.symbol_AWG'] = '&#402;';
$_lang['currencyconverter.symbol_AZN'] = '&#1084;&#1072;&#1085;';
$_lang['currencyconverter.symbol_BAM'] = '&#75;&#77;';
$_lang['currencyconverter.symbol_BBD'] = '&#36;';
$_lang['currencyconverter.symbol_BDT'] = '&#2547;'; // ?
$_lang['currencyconverter.symbol_BGN'] = '&#1083;&#1074;';
$_lang['currencyconverter.symbol_BHD'] = '.&#1583;.&#1576;'; // ?
$_lang['currencyconverter.symbol_BIF'] = '&#70;&#66;&#117;'; // ?
$_lang['currencyconverter.symbol_BMD'] = '&#36;';
$_lang['currencyconverter.symbol_BND'] = '&#36;';
$_lang['currencyconverter.symbol_BOB'] = '&#36;&#98;';
$_lang['currencyconverter.symbol_BRL'] = '&#82;&#36;';
$_lang['currencyconverter.symbol_BSD'] = '&#36;';
$_lang['currencyconverter.symbol_BTN'] = '&#78;&#117;&#46;'; // ?
$_lang['currencyconverter.symbol_BWP'] = '&#80;';
$_lang['currencyconverter.symbol_BYR'] = '&#112;&#46;';
$_lang['currencyconverter.symbol_BZD'] = '&#66;&#90;&#36;';
$_lang['currencyconverter.symbol_CAD'] = '&#36;';
$_lang['currencyconverter.symbol_CDF'] = '&#70;&#67;';
$_lang['currencyconverter.symbol_CHF'] = '&#67;&#72;&#70;';
$_lang['currencyconverter.symbol_CLF'] = ''; // ?
$_lang['currencyconverter.symbol_CLP'] = '&#36;';
$_lang['currencyconverter.symbol_CNY'] = '&#165;';
$_lang['currencyconverter.symbol_COP'] = '&#36;';
$_lang['currencyconverter.symbol_CRC'] = '&#8353;';
$_lang['currencyconverter.symbol_CUP'] = '&#8396;';
$_lang['currencyconverter.symbol_CVE'] = '&#36;'; // ?
$_lang['currencyconverter.symbol_CZK'] = '&#75;&#269;';
$_lang['currencyconverter.symbol_DJF'] = '&#70;&#100;&#106;'; // ?
$_lang['currencyconverter.symbol_DKK'] = '&#107;&#114;';
$_lang['currencyconverter.symbol_DOP'] = '&#82;&#68;&#36;';
$_lang['currencyconverter.symbol_DZD'] = '&#1583;&#1580;'; // ?
$_lang['currencyconverter.symbol_EEK'] = '&#75;&#82;';
$_lang['currencyconverter.symbol_EGP'] = '&#163;';
$_lang['currencyconverter.symbol_ETB'] = '&#66;&#114;';
$_lang['currencyconverter.symbol_EUR'] = '&#8364;';
$_lang['currencyconverter.symbol_FJD'] = '&#36;';
$_lang['currencyconverter.symbol_FKP'] = '&#163;';
$_lang['currencyconverter.symbol_GBP'] = '&#163;';
$_lang['currencyconverter.symbol_GEL'] = '&#4314;'; // ?
$_lang['currencyconverter.symbol_GHS'] = '&#162;';
$_lang['currencyconverter.symbol_GIP'] = '&#163;';
$_lang['currencyconverter.symbol_GMD'] = '&#68;'; // ?
$_lang['currencyconverter.symbol_GNF'] = '&#70;&#71;'; // ?
$_lang['currencyconverter.symbol_GTQ'] = '&#81;';
$_lang['currencyconverter.symbol_GYD'] = '&#36;';
$_lang['currencyconverter.symbol_HKD'] = '&#36;';
$_lang['currencyconverter.symbol_HNL'] = '&#76;';
$_lang['currencyconverter.symbol_HRK'] = '&#107;&#110;';
$_lang['currencyconverter.symbol_HTG'] = '&#71;'; // ?
$_lang['currencyconverter.symbol_HUF'] = '&#70;&#116;';
$_lang['currencyconverter.symbol_IDR'] = '&#82;&#112;';
$_lang['currencyconverter.symbol_ILS'] = '&#8362;';
$_lang['currencyconverter.symbol_INR'] = '&#8377;';
$_lang['currencyconverter.symbol_IQD'] = '&#1593;.&#1583;'; // ?
$_lang['currencyconverter.symbol_IRR'] = '&#65020;';
$_lang['currencyconverter.symbol_ISK'] = '&#107;&#114;';
$_lang['currencyconverter.symbol_JEP'] = '&#163;';
$_lang['currencyconverter.symbol_JMD'] = '&#74;&#36;';
$_lang['currencyconverter.symbol_JOD'] = '&#74;&#68;'; // ?
$_lang['currencyconverter.symbol_JPY'] = '&#165;';
$_lang['currencyconverter.symbol_KES'] = '&#75;&#83;&#104;'; // ?
$_lang['currencyconverter.symbol_KGS'] = '&#1083;&#1074;';
$_lang['currencyconverter.symbol_KHR'] = '&#6107;';
$_lang['currencyconverter.symbol_KMF'] = '&#67;&#70;'; // ?
$_lang['currencyconverter.symbol_KPW'] = '&#8361;';
$_lang['currencyconverter.symbol_KRW'] = '&#8361;';
$_lang['currencyconverter.symbol_KWD'] = '&#1583;.&#1603;'; // ?
$_lang['currencyconverter.symbol_KYD'] = '&#36;';
$_lang['currencyconverter.symbol_KZT'] = '&#1083;&#1074;';
$_lang['currencyconverter.symbol_LAK'] = '&#8365;';
$_lang['currencyconverter.symbol_LBP'] = '&#163;';
$_lang['currencyconverter.symbol_LKR'] = '&#8360;';
$_lang['currencyconverter.symbol_LRD'] = '&#36;';
$_lang['currencyconverter.symbol_LSL'] = '&#76;'; // ?
$_lang['currencyconverter.symbol_LTL'] = '&#76;&#116;';
$_lang['currencyconverter.symbol_LVL'] = '&#76;&#115;';
$_lang['currencyconverter.symbol_LYD'] = '&#1604;.&#1583;'; // ?
$_lang['currencyconverter.symbol_MAD'] = '&#1583;.&#1605;.'; //?
$_lang['currencyconverter.symbol_MDL'] = '&#76;';
$_lang['currencyconverter.symbol_MGA'] = '&#65;&#114;'; // ?
$_lang['currencyconverter.symbol_MKD'] = '&#1076;&#1077;&#1085;';
$_lang['currencyconverter.symbol_MMK'] = '&#75;';
$_lang['currencyconverter.symbol_MNT'] = '&#8366;';
$_lang['currencyconverter.symbol_MOP'] = '&#77;&#79;&#80;&#36;'; // ?
$_lang['currencyconverter.symbol_MRO'] = '&#85;&#77;'; // ?
$_lang['currencyconverter.symbol_MUR'] = '&#8360;'; // ?
$_lang['currencyconverter.symbol_MVR'] = '.&#1923;'; // ?
$_lang['currencyconverter.symbol_MWK'] = '&#77;&#75;';
$_lang['currencyconverter.symbol_MXN'] = '&#36;';
$_lang['currencyconverter.symbol_MYR'] = '&#82;&#77;';
$_lang['currencyconverter.symbol_MZN'] = '&#77;&#84;';
$_lang['currencyconverter.symbol_NAD'] = '&#36;';
$_lang['currencyconverter.symbol_NGN'] = '&#8358;';
$_lang['currencyconverter.symbol_NIO'] = '&#67;&#36;';
$_lang['currencyconverter.symbol_NOK'] = '&#107;&#114;';
$_lang['currencyconverter.symbol_NPR'] = '&#8360;';
$_lang['currencyconverter.symbol_NZD'] = '&#36;';
$_lang['currencyconverter.symbol_OMR'] = '&#65020;';
$_lang['currencyconverter.symbol_PAB'] = '&#66;&#47;&#46;';
$_lang['currencyconverter.symbol_PEN'] = '&#83;&#47;&#46;';
$_lang['currencyconverter.symbol_PGK'] = '&#75;'; // ?
$_lang['currencyconverter.symbol_PHP'] = '&#8369;';
$_lang['currencyconverter.symbol_PKR'] = '&#8360;';
$_lang['currencyconverter.symbol_PLN'] = '&#122;&#322;';
$_lang['currencyconverter.symbol_PYG'] = '&#71;&#115;';
$_lang['currencyconverter.symbol_QAR'] = '&#65020;';
$_lang['currencyconverter.symbol_RON'] = '&#108;&#101;&#105;';
$_lang['currencyconverter.symbol_RSD'] = '&#1044;&#1080;&#1085;&#46;';
$_lang['currencyconverter.symbol_RUB'] = '&#1088;&#1091;&#1073;';
$_lang['currencyconverter.symbol_RWF'] = '&#1585;.&#1587;';
$_lang['currencyconverter.symbol_SAR'] = '&#65020;';
$_lang['currencyconverter.symbol_SBD'] = '&#36;';
$_lang['currencyconverter.symbol_SCR'] = '&#8360;';
$_lang['currencyconverter.symbol_SDG'] = '&#163;'; // ?
$_lang['currencyconverter.symbol_SEK'] = '&#107;&#114;';
$_lang['currencyconverter.symbol_SGD'] = '&#36;';
$_lang['currencyconverter.symbol_SHP'] = '&#163;';
$_lang['currencyconverter.symbol_SLL'] = '&#76;&#101;'; // ?
$_lang['currencyconverter.symbol_SOS'] = '&#83;';
$_lang['currencyconverter.symbol_SRD'] = '&#36;';
$_lang['currencyconverter.symbol_STD'] = '&#68;&#98;'; // ?
$_lang['currencyconverter.symbol_SVC'] = '&#36;';
$_lang['currencyconverter.symbol_SYP'] = '&#163;';
$_lang['currencyconverter.symbol_SZL'] = '&#76;'; // ?
$_lang['currencyconverter.symbol_THB'] = '&#3647;';
$_lang['currencyconverter.symbol_TJS'] = '&#84;&#74;&#83;'; // ? TJS (guess)
$_lang['currencyconverter.symbol_TMT'] = '&#109;';
$_lang['currencyconverter.symbol_TND'] = '&#1583;.&#1578;';
$_lang['currencyconverter.symbol_TOP'] = '&#84;&#36;';
$_lang['currencyconverter.symbol_TRY'] = '&#8356;'; // New Turkey Lira (old symbol used)
$_lang['currencyconverter.symbol_TTD'] = '&#36;';
$_lang['currencyconverter.symbol_TWD'] = '&#78;&#84;&#36;';
$_lang['currencyconverter.symbol_TZS'] = '';
$_lang['currencyconverter.symbol_UAH'] = '&#8372;';
$_lang['currencyconverter.symbol_UGX'] = '&#85;&#83;&#104;';
$_lang['currencyconverter.symbol_USD'] = '&#36;';
$_lang['currencyconverter.symbol_UYU'] = '&#36;&#85;';
$_lang['currencyconverter.symbol_UZS'] = '&#1083;&#1074;';
$_lang['currencyconverter.symbol_VEF'] = '&#66;&#115;';
$_lang['currencyconverter.symbol_VND'] = '&#8363;';
$_lang['currencyconverter.symbol_VUV'] = '&#86;&#84;';
$_lang['currencyconverter.symbol_WST'] = '&#87;&#83;&#36;';
$_lang['currencyconverter.symbol_XAF'] = '&#70;&#67;&#70;&#65;';
$_lang['currencyconverter.symbol_XCD'] = '&#36;';
$_lang['currencyconverter.symbol_XDR'] = '';
$_lang['currencyconverter.symbol_XOF'] = '';
$_lang['currencyconverter.symbol_XPF'] = '&#70;';
$_lang['currencyconverter.symbol_YER'] = '&#65020;';
$_lang['currencyconverter.symbol_ZAR'] = '&#82;';
$_lang['currencyconverter.symbol_ZMK'] = '&#90;&#75;'; // ?
$_lang['currencyconverter.symbol_ZWL'] = '&#90;&#36;';
